### PR TITLE
Identifies SV keywords used as identifiers

### PR DESCRIPTION
**Pull request by nblei**
For issue #712

I added a `var_declaration` definition for `CheckIdentifier`.  In it, I do not call `check`, but rather just do the work in the `var_declaration` function itself --- perhaps this should be merged into `check`?

### CODE REVIEW

**Comment by dalance** [comment]
> perhaps this should be merged into check?

Yes. `check` is called at arbitrary identifier definition not limited to `var_declaration`.
So if the `is_sv_keyword` is merged into `check`, other identifier like param, function, and so on will be checked too.

**Comment by nblei** [comment]
> > perhaps this should be merged into check?
> 
> Yes. `check` is called at arbitrary identifier definition not limited to `var_declaration`. So if the `is_sv_keyword` is merged into `check`, other identifier like param, function, and so on will be checked too.

OK, I'm just running the SV keyword checks in `check` now.

**Comment by dalance** [comment]
Could you add test for `SvKeywordUsage` error at `crates/analyzer/src/tests.rs`?

**Comment by nblei** [comment]
> Could you add test for `SvKeywordUsage` error at `crates/analyzer/src/tests.rs`?

Done.

**Pull request merged**
